import antfu from '@antfu/eslint-config'

/**
 * Flat config for ESLint 9+/10（替代旧 .eslintrc）。
 * 存量模板以 CI 可运行为先：关闭风格/偏好类规则，后续可逐步收紧。
 */
export default antfu({
  vue: true,
  typescript: true,
  stylistic: false,
  formatters: false,
  jsonc: false,
  yaml: false,
  markdown: false,
  ignores: [
    '**/dist/**',
    '**/dist-electron/**',
    '**/test/**',
    '**/public/**',
    '**/electron/**',
    '**/scripts/**',
    '**/mock/**',
    '**/node_modules/**',
    '**/*.d.ts',
    '**/components/bpmnProcessDesigner/**',
    '**/components/SimpleProcessDesigner/**',
    '**/components/Icon/**',
    '.eslint-out.json',
  ],
  rules: {
    'no-console': 'off',
    'no-alert': 'off',
    'no-labels': 'off',
    'no-new': 'off',
    'no-useless-rename': 'off',
    'no-useless-catch': 'off',
    'prefer-template': 'off',
    'prefer-const': 'off',
    'prefer-promise-reject-errors': 'off',
    'object-shorthand': 'off',
    'eqeqeq': 'off',
    'antfu/if-newline': 'off',
    'antfu/top-level-function': 'off',
    'e18e/prefer-includes': 'off',
    'e18e/prefer-nullish-coalescing': 'off',
    'ts/no-explicit-any': 'off',
    'ts/ban-ts-comment': 'off',
    'ts/no-unused-vars': 'off',
    'ts/consistent-type-imports': 'off',
    'ts/consistent-type-definitions': 'off',
    'ts/no-use-before-define': 'off',
    'ts/no-empty-function': 'off',
    'ts/no-import-type-side-effects': 'off',
    'ts/no-unsafe-function-type': 'off',
    'ts/no-unused-expressions': 'off',
    'unused-imports/no-unused-vars': 'off',
    'unused-imports/no-unused-imports': 'off',
    'one-var': 'off',
    'no-control-regex': 'off',
    'e18e/prefer-timer-args': 'off',
    'regexp/strict': 'off',
    'regexp/no-useless-flag': 'off',
    'jsdoc/check-param-names': 'off',
    'vue/prefer-template': 'off',
    'import/consistent-type-specifier-style': 'off',
    'import/first': 'off',
    'import/order': 'off',
    'import/no-duplicates': 'off',
    'perfectionist/sort-imports': 'off',
    'perfectionist/sort-named-imports': 'off',
    'perfectionist/sort-named-exports': 'off',
    'perfectionist/sort-exports': 'off',
    'perfectionist/sort-objects': 'off',
    'unicorn/prefer-number-properties': 'off',
    'unicorn/prefer-node-protocol': 'off',
    'unicorn/number-literal-case': 'off',
    'unicorn/prefer-string-starts-ends-with': 'off',
    'unicorn/prefer-includes': 'off',
    'node/prefer-global/process': 'off',
    'regexp/no-super-linear-backtracking': 'off',
    'regexp/no-unused-capturing-group': 'off',
    'regexp/prefer-range': 'off',
    'regexp/no-dupe-characters-character-class': 'off',
    'regexp/no-useless-escape': 'off',
    'regexp/prefer-d': 'off',
    'regexp/use-ignore-case': 'off',
    'regexp/no-useless-quantifier': 'off',
    'regexp/no-useless-character-class': 'off',
    'regexp/control-character-escape': 'off',
    'regexp/no-useless-non-capturing-group': 'off',
    'regexp/prefer-w': 'off',
    'vue/no-unused-refs': 'off',
    'vue/no-unused-vars': 'off',
    'vue/require-explicit-emits': 'off',
    'vue/html-self-closing': 'off',
    'vue/attributes-order': 'off',
    'vue/eqeqeq': 'off',
    'vue/custom-event-name-casing': 'off',
    'vue/no-mutating-props': 'off',
    'vue/one-component-per-file': 'off',
    'vue/component-name-in-template-casing': 'off',
    'vue/block-order': 'off',
    'vue/define-macros-order': 'off',
    'vue/component-definition-name-casing': 'off',
    'vue/singleline-html-element-content-newline': 'off',
    'vue/multiline-html-element-content-newline': 'off',
    'vue/html-indent': 'off',
    'vue/max-attributes-per-line': 'off',
    'vue/first-attribute-linebreak': 'off',
    'vue/html-closing-bracket-newline': 'off',
    'vue/no-setup-props-destructure': 'off',
    'vue/prefer-separate-static-class': 'off',
    'vue/attribute-hyphenation': 'off',
    'vue/no-useless-v-bind': 'off',
    'vue/no-deprecated-filter': 'off',
    'vue/html-quotes': 'off',
    'vue/no-reserved-component-names': 'off',
  },
})
